name: bg3.9
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.16.0=he5ede1b_6
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hf296adc_0
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h516909a_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.14=h993c535_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - black==22.1.0
      - bleach==6.2.0
      - bokeh==3.3.4
      - cachetools==6.1.0
      - casadi==3.7.0
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dill==0.3.4
      - einops==0.6.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - execnet==2.1.1
      - executing==2.2.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - fire==0.7.0
      - fonttools==4.58.5
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - isort==5.10.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - kornia==0.6.4
      - l5kit==1.5.0
      - lightning-utilities==0.14.3
      - markupsafe==3.0.2
      - matplotlib==3.5.0
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.4
      - notebook-shim==0.2.4
      - numcodecs==0.12.1
      - numpy==1.19.5
      - nuscenes-devkit==1.1.9
      - opencv-contrib-python-headless==4.11.0.86
      - opencv-python==4.11.0.86
      - overrides==7.7.0
      - packaging==25.0
      - pandas==1.4.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==3.20.1
      - psutil==7.0.0
      - ptable==0.9.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py==1.11.0
      - pyarrow==7.0.0
      - pycocotools==2.0.10
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyemd==1.0.0
      - pygments==2.19.2
      - pymap3d==3.1.0
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pytest==7.1.1
      - pytest-forked==1.6.0
      - pytest-xdist==2.5.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytorch-lightning==1.9.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - referencing==0.36.2
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.26.0
      - scikit-learn==1.6.1
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.3
      - sentry-sdk==2.32.0
      - setuptools-scm==8.3.1
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==1.11.0+cu113
      - torchaudio==0.11.0+cu113
      - torchmetrics==0.11.1
      - torchtext==0.12.0
      - torchvision==0.12.0+cu113
      - tornado==6.5.1
      - tqdm==4.62.0
      - traitlets==5.14.3
      - trajdata==1.2.1
      - transforms3d==0.4.2
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.21.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - xyzservices==2025.4.0
      - yarl==1.20.1
      - zarr==2.11.0
      - zipp==3.23.0
prefix: /users/cw3005/anaconda3/envs/bg3.9
